# REMEMBER TO EDIT THIS BEFORE DEPLOYING!!!

# the path to your blog's icon:
favicon: /favicon.png

# the path to manifest.json
manifest: /manifest.json

# [Open Graph Protocol](https://ogp.me/)
og_enabled: true
og_image: /favicon.png
og:
  # customize og properties here which will replace the defaults

# show excerpt on post list
show_excerpt: false

# light/dark/auto color scheme
color_scheme: auto

# show floating color theme toggle
show_color_scheme_toggle: true

# uppercase categories
uppercase_categories: true

# capitalize tag names on tags page
capitalize_tags: false

# add hashtag prefix before tags
hashtag_prefix_before_tags: true

# rainbow!
rainbow_banner: true
rainbow_banner_colors:
  - '#e50000'
  - '#ff8d00'
  - '#ffee00'
  - '#008121'
  - '#004cff'
  - '#760188'
# choose from [auto, always]
rainbow_banner_shown: auto
# Pride Month by default
rainbow_banner_month: 6

# TOC - table of contents
toc: true
toc_max_depth: 2

# scroll reveal (https://scrollrevealjs.org/) - animating elements as they enter/leave the viewport
scroll_reveal: true

# navigation config
nav:
  # the title displays in the upper left corner which won't change
  title: Blog
  # the items displays in the upper right corner
  items:
    # these items will display as a link
    Archives: /archives
    Friends: /friends
    Projects: /projects
    About: /about
    # these will be automatically be an icon
    GitHub: https://github.com/MrWillCom
    CodePen: https://codepen.io/mrwillcom
    Patreon: https://www.patreon.com/MrWillCom
    Mastodon: https://noc.social/@MrWillCom
    Discord: https://discord.gg/UKuFDjcfY8
    Search: /search

# footer items
footer:
  # the title
  Blog:
    # the items after the title, display as links
    Blog: /
    Archives: /archives
    Tags: /tags
    Categories: /categories
    Search: /search
    Friends: /friends
    Projects: /projects
    Resume: /resume
    About: /about
    RSS: /atom.xml
  # also the title
  Projects:
    # the items
    RSA CLI: https://github.com/MrWillCom/rsa-cli
    Hexo Theme Cupertino: https://github.com/MrWillCom/hexo-theme-cupertino
    A Calendar: https://github.com/MrWillCom/a-calendar
    Auto Mirroring Bucket: https://github.com/MrWillCom/auto-mirroring-bucket
  # the title
  Me:
    # items
    GitHub: https://github.com/MrWillCom
    CodePen: https://codepen.io/mrwillcom
    Patreon: https://www.patreon.com/MrWillCom
    Mastodon: https://noc.social/@MrWillCom
    Discord: https://discord.gg/UKuFDjcfY8
    Email: mailto:mr.will.com@outlook.com

# footer extra description
# footer_extra_description: something will be shown at the bottom of the footer

# the license your posts under
license: CC BY-NC 4.0
# the link of your license
license_link: https://creativecommons.org/licenses/by-nc/4.0

# search
# based on [hexo-generator-search](https://github.com/wzpan/hexo-generator-search)
search: true
search_path: search.json

# REMEMBER TO EDIT THIS BEFORE DEPLOYING!!!